version: '3'
services:
  nginx:
    build:
      context: ./      
      dockerfile: Dockerfile
      args:
        - NGINX_VERSION=1.25.2
    image: waesy/nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-available:/etc/nginx/sites-available
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/letsencrypt:/etc/letsencrypt
      - ./public:/var/www/public
    networks:
      - net_swarm
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 20M
      restart_policy:
        condition: on-failure

networks:
  net_swarm:
    external: true
    name: net_swarm